# Generated by Django 5.1.2 on 2024-10-12 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_color_code_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1000 TO 5000', '1000 TO 5000'), ('5000 TO 10000', '5000 TO 10000'), ('10000 TO 25000', '10000 TO 25000'), ('25000 TO 50000', '25000 TO 50000'), ('50000 TO 100000', '50000 TO 100000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
